services:
  auction.database:
    image: postgres
    container_name: auction.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: auction
    ports:
      - 1234:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
