networks:
  mynetwork:
services:
  auction.database:
    image: postgres
    container_name: auction.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: auction
    ports:
      - 1234:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auction"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  search.database:
    image: mongo
    container_name: search.mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork    
  eventbus.rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
volumes:
  postgres_data:
  mongodata: