services:
  auction.database:
    image: postgres
    container_name: auction.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: auction
    ports:
      - 1234:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  search.database:
    image: mongo
    container_name: search.mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  eventbus.rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data:
  mongodata: